apiVersion: v1
kind: ConfigMap
metadata:
  name: diffwatcher
data:
  .diffwatcher.yaml: |
    namespace: ""
    handler:
      slack:
        token: <token>
        channel: <channel>
    resource:
      deployment: false
      replicationcontroller: false
      replicaset: false
      daemonset: false
      statefulset: false
      services: true
      pod: true
      secret: false
      configmap: false
      hpa: false
      coreevent: false
      event: true
