apiVersion: v1
kind: ConfigMap
metadata:
  name: diffwatcher
data:
  .diffwatcher.yaml: |
    namespace:
    handler:
      msteams:
        webhookurl: https://outlook.office.com/webhook/...
    resource:
      namespace: false
      deployment: false
      replicationcontroller: false
      replicaset: false
      daemonset: false
      services: false
      pod: true
      secret: false
      configmap: false
